#ifndef KONFIGURACJA
#define KONFIGURACJA

#define TYP Graf //Tablica_hash //Drzewo //
#define PIERWSZY_ZNAK 'a'
#define ILOSC_MOZLIWYCH_ZNAKOW  ('z'-'a'+1)
#define ILOSC_SPRAWDZANYCH_ZNAKOW 3
#define POCZATKOWY_ROZMIAR_TABLICY (pow(ILOSC_MOZLIWYCH_ZNAKOW,ILOSC_SPRAWDZANYCH_ZNAKOW))
#define MAKSYMALNA_DLUGOSC_SLOWA 3
#define MINIMALNA_WARTOSC 0
#define MAKSYMALNA_WARTOSC 100
#define ILOSC_DANYCH 100000
#define ILE_RAZY_POWTORZYC 1

#endif
